# Generated by Django 5.0.3 on 2024-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Livre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=50)),
                ("auteur", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="files/cover")),
            ],
        ),
    ]
